export const UI_START_LOADING = 'UI_START_LOADING';
export const UI_STOP_LOADING = 'UI_STOP_LOADING';

export const USER_ADD_MESSAGE = 'USER_ADD_MESSAGE';
export const CHATBOT_ADD_MESSAGE = 'CHATBOT_ADD_MESSAGE';